### ISSUE TITLE
Arrow drawing issue in Janggi

### ISSUE THREAD

**Issue by gbtami** [gbtami/chessgroundx#31] opened 2022-02-25 23:35 UTC
PraseodymiumSpike: The arrow drawing feature is kind of broken for Janggi right now as you can't draw arrows for the elephant.
PraseodymiumSpike: As in you can't draw arrows to a point (2,3) away.

**Comment by gbtami** [comment] 2022-03-23 09:41
@Fulmene you mentioned in pychess lobby chat that you remember what is the root of this issue. I can't :)

**Comment by Fulmene** [comment] 2022-03-29 08:34
Currently, a (2,3) arrow can still be drawn by moving the mouse off the board and back again for a "free style" mode.

[This](https://github.com/gbtami/chessgroundx/blob/master/src/board.ts#L383) is where the problem is. Now that I checked it, I even commented on this when I first merged the feature :D

Since the function has no way to know what variant is being in effect (by design) though, adding Janggi Elephant here will affect all variants. It's why I'm still unsure about adding the arrow snap.

**Comment by Fulmene** [comment] 2022-03-29 15:24
The restriction is very practical though. In Chess, and most variants on pychess, all movements are subsets of Q+N, so adding this restriction eliminates all problems caused by any slight mouse slips, especially for long arrows. At least, someone found it useful enough to [work on it](https://github.com/lichess-org/chessground/pull/146). Besides, freestyle arrow is still possible with the "moving off the board" gesture, so I don't see a reason to remove the snap completely at all.

The question is: Do we allow Janggi Elephant arrow? On one hand, doing so will worsen the experience of drawing other pieces' (Bishop, Queen, Xiangqi Elephant) length-2 diagonal arrows. On the other hand, it's still an improvement over completely freestyle drawing. I personally don't have any strong views either way.

Maybe we should take this discussion to Discord for more opinions.

**Comment by Fulmene** [comment] 2022-03-29 17:43
Fixed in [ac68943](https://github.com/gbtami/chessgroundx/commit/ac68943f940365c50567b0d9c3116559e8c1f92e)

**Closed by Fulmene** 2022-03-29 17:43 UTC
Labels: bug
